name: Benchmarking

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ] 

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        nineties: [90s, ""]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run Benches
        run: |
          if [ -z "${{ matrix.nineties }}" ]; then
            cargo bench --features "benchmarking"
          else
            cargo bench --features "benchmarking ${{ matrix.nineties }}"
          fi
